version: '3'
services:
  <%= appName%>_node:
   container_name: <%= appName%>_node
   build:
    context: .
    args:
     - NODE_ENV=development
   working_dir: /usr/src/app
   command: npm run build
   volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
   ports:
    - 3000:3000
   depends_on:
    - db-<%= dbType%>
   links:
    - db-<%= dbType%>
   env_file:
    - .env
  db-<%= dbType%>:
   image: <%= dbImage%>
   container_name: db-<%= dbType%>
   volumes:
    - .data/db/<%= dbImage%>:<%=dbPath%>
   ports:
   - <%= dbPorts%>
